try_catch() is
    try

    let x = 1;

    catch

    return;

    let y = 10;
si
