namespace Test is











    use Std = IO.Std;


    use BoundsException = System.IndexOutOfRangeException;

    class Main is
        entry() static is
            

            try
                Std.out.write_line("do stuff");
            catch ex: string
                Std.out.write_line("string is not catchable");
            catch ex: MyException
                Std.out.write_line("derived exception class is catchable");
            catch ex: System.Exception
                Std.out.write_line("root exception class is catchable"); 
            catch ex: int
                Std.out.write_line("int is not catchable");
            finally
                Std.out.write_line("done stuff");
            yrt
            
            return;
        si
    si

    class MyException: BoundsException is
        
    si    
si