internal: 1,1..1,2: error: caught exception running pass compile-expressions count: 0 on work item test.ghul
test.ghul: 10,24..10,34: error: cannot use this here
test.ghul: 10,24..10,34: error: no overload found for write_line(entry(...)), tried IO.Std.write_line(buffer: Ghul.char[]) -> Ghul.void, IO.Std.write_line(value: Decimal) -> Ghul.void, IO.Std.write_line(value: bool) -> Ghul.void, IO.Std.write_line(value: char) -> Ghul.void, IO.Std.write_line(value: double) -> Ghul.void, IO.Std.write_line(value: int) -> Ghul.void, IO.Std.write_line(value: long) -> Ghul.void, IO.Std.write_line(value: object) -> Ghul.void, IO.Std.write_line(value: single) -> Ghul.void, IO.Std.write_line(value: string) -> Ghul.void, IO.Std.write_line(value: uint) -> Ghul.void, IO.Std.write_line(value: ulong) -> Ghul.void
test.ghul: 12,16..12,20: error: cannot use this here
test.ghul: 12,24..12,28: error: cannot use this here
test.ghul: 16,19..16,23: error: cannot use this here
test.ghul: 23,20..23,21: error: cannot use this as a type
test.ghul: 25,17..25,21: error: cannot use this here
test.ghul: 26,13..26,27: error: entry(...) is not assignable to Ghul.object
test.ghul: 26,17..26,27: error: cannot use this here
test.ghul: 28,21..28,31: error: cannot use this here
test.ghul: 30,13..30,17: error: something went wrong with identifier
test.ghul: 4,5..44,7: error: exception walking class syntax tree
test.ghul: 9,24..9,28: error: cannot use this here
