namespace Test is











    use IO.Std;
    use BoundsException = System.IndexOutOfRangeException;

    use System.Exception;

    class Main is
        entry() static is
            

            test("expect nothing", null);

            test("expect my exception catch", MyException("my exception"));

            test("expect other exception catch", Exception("system exception"));

            test("expect other exception catch", BoundsException("bounds exception"));
        si

        test(message: string, ex: Exception) static is
            Std.out.write_line("before: " + message);

            try
                Std.out.write_line("start: " + message);

                if ex? then
                    Std.out.write_line("will throw: " + ex.get_type().name);

                    throw ex;

                    Std.out.write_line("should not be reachable");
                else
                    Std.out.write_line("will not throw");                    
                fi
                
            catch ex: MyException
                Std.out.write_line("caught my exception: " + ex.message);

            catch ex: Exception
                Std.out.write_line("caught other exception: " + ex.message);

            yrt

            Std.out.write_line("after: " + message);
        si        
    si

    class MyException: Exception is
        init(message: string) is
            super.init(message);
        si
    si    
si